name: Deploy index.html & main.js to EC2

on:
  push:
    branches: [ main ]
    paths:
      - "index.html"       # 루트 index.html 변경 시
      - "src/main.js"      # src 폴더 안 main.js 변경 시

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ EC2 타겟 디렉토리 존재 확인 및 생성
      - name: Ensure target directory exists
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p ${{ secrets.EC2_TARGET_DIR }}

      # 3️⃣ 파일 EC2로 복사
      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "index.html,src/main.js"
          target: ${{ secrets.EC2_TARGET_DIR }}
